require("core.options")
require("core.keymaps")
require("core.autocmds")
require("core.statusline")

require("plugins.themes.lackluster")
require("plugins.git")
require("plugins.oil")
require("plugins.treesitter")
require("plugins.fzf")
