require("core.options")
require("core.keymaps")
require("core.autocmds")
require("core.statusline")
require("core.lsp")

require("plugins.themes.lackluster")
require("plugins.git")
require("plugins.oil")
require("plugins.treesitter")
require("plugins.fzf")
require("plugins.mason")
require("plugins.fidget")
require("plugins.blink")
require("plugins.conform")
require("plugins.harpoon")
