---
- hosts: localhost
  become: false

  # ==============================================
  #       Give Me Fuel Give Me Fire Installation
  # ==============================================

  tasks:
    # ----------------------------------------------
    #                    Git Installation
    # ----------------------------------------------

    - name: Install Git
      homebrew:
        name: git
        state: present
      register: git_installation
      tags: git

    - name: Output Git installation results
      debug:
        var: git_installation.stdout

    # ----------------------------------------------
    #               Zsh & Starship Setup
    # ----------------------------------------------

    - name: Install zsh
      tags: zsh
      homebrew:
        name: zsh
        state: present
      register: zsh_installation

    - name: Output Zsh installation results
      debug:
        var: zsh_installation.stdout

    # ----------------------------------------------

    - name: Install Starship prompt using Homebrew
      tags: starship
      homebrew:
        name: starship
        state: present
      when: ansible_facts.packages.starship is not defined
      register: starship_installation

    - name: Output Starship installation results
      debug:
        var: starship_installation
    # ----------------------------------------------

    - name: Configure Starship prompt in .zshrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'eval "$(starship init zsh)"'
        create: yes

    # ----------------------------------------------
    #              Zsh Plugin Installation
    # ----------------------------------------------

    - name: Clone zsh-autosuggestions plugin
      tags: zsh
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "{{ ansible_env.HOME }}/.zsh/plugins/zsh-autosuggestions"
        version: master
      when: not ansible_env.HOME | regex_search('.*zsh-autosuggestions.*') # Check if the plugin is already installed

    - name: Output zsh-autosuggestions installation results
      debug:
        msg: "zsh-autosuggestions plugin cloned to {{ ansible_env.HOME }}/.zsh/plugins/zsh-autosuggestions"
    # ----------------------------------------------

    - name: Clone zsh-syntax-highlighting plugin
      tags: zsh
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "{{ ansible_env.HOME }}/.zsh/plugins/zsh-syntax-highlighting"
        version: master
      when: not ansible_env.HOME | regex_search('.*zsh-syntax-highlighting.*') # Check if the plugin is already installed

    - name: Output zsh-syntax-highlighting installation results
      debug:
        msg: "zsh-syntax-highlighting plugin cloned to {{ ansible_env.HOME }}/.zsh/plugins/zsh-syntax-highlighting"

    # ----------------------------------------------
    #               Update .zshrc Configuration
    # ----------------------------------------------

    - name: Ensure zsh-autosuggestions is sourced in .zshrc
      tags: zsh
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        regexp: "^source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh$"
        line: "source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"
        create: yes

    - name: Ensure zsh-syntax-highlighting is sourced last in .zshrc
      tags: zsh
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        regexp: "^source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh$"
        line: "source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
        create: yes
        insertafter: EOF

    - name: Output .zshrc configuration results
      debug:
        msg: ".zshrc updated with zsh-autosuggestions and zsh-syntax-highlighting plugins"

    # ----------------------------------------------
    #            Get .dotfiles from git
    # ----------------------------------------------

    - name: Clone dotfiles repository
      tags: dotfiles
      git:
        repo: https://github.com/dsomleff/dotfiles
        dest: "{{ ansible_env.HOME }}/dotfiles"
        version: main

    - name: Output dotfiles clone results
      debug:
        msg: "Dotfiles cloned to {{ ansible_env.HOME }}/dotfiles"

    # ----------------------------------------------
    #            Replace .zshrc with Custom Version
    # ----------------------------------------------

    - name: Replace .zshrc with custom version
      tags: zshrc
      copy:
        src: "{{ ansible_env.HOME }}/dotfiles/.zshrc" # Path to your custom .zshrc in the cloned repo
        dest: "{{ ansible_env.HOME }}/.zshrc" # Path to the target .zshrc
        remote_src: yes # Indicate that the source file is already on the remote machine
        force: yes # Force replacement even if the file exists

    - name: Output .zshrc replacement results
      debug:
        msg: ".zshrc replaced with custom version"

    # ----------------------------------------------
    #            Install all brew packages
    # ----------------------------------------------

    - name: Run Brew setup script
      tags: brew
      shell: bash "{{ ansible_env.HOME }}/dotfiles/setup_macos/setup_brew.sh"
      register: brew_setup
      ignore_errors: yes # Optional: ignore errors if the script fails for some reason

    - name: Output Brew setup results
      debug:
        var: brew_setup.stdout

    # ----------------------------------------------
    #            Install local scripts
    # ----------------------------------------------

    - name: Run update-alacritty-icon script
      tags: local-scripts
      shell: bash "{{ ansible_env.HOME }}/dotfiles/.local/scripts/update-alacritty-icon.sh"
      register: alacritty_icon_script
      ignore_errors: yes # Optional: ignore errors if the script fails for some reason

    - name: Output results of update-alacritty-icon script
      debug:
        var: alacritty_icon_script.stdout

    # ==============================================
    #                Run System Settings Script
    # ==============================================

    - name: Run System settings script
      tags: macos
      shell: bash "{{ ansible_env.HOME }}/dotfiles/setup_macos/system_settings.sh"
      register: system_settings_setup

    - name: Output System settings setup results
      debug:
        var: system_settings_setup.stdout
